# Generated by Django 4.0.1 on 2022-01-21 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='theme',
        ),
    ]
