# Generated by Django 4.0.1 on 2022-01-24 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0006_question_question_delete_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='choice_text',
        ),
    ]
