# Generated by Django 4.0.1 on 2022-01-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0007_rename_question_question_choice_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='choice_text',
            new_name='choice_text_1',
        ),
        migrations.AddField(
            model_name='question',
            name='choice_text_2',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='choice_text_3',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='choice_text_4',
            field=models.CharField(default=4, max_length=200),
            preserve_default=False,
        ),
    ]
