# Generated by Django 4.0.1 on 2022-01-25 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0008_rename_choice_text_question_choice_text_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choice_text_1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_text_2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_text_3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_text_4',
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz.question')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz.theme')),
            ],
        ),
    ]
