# Generated by Django 4.0.1 on 2022-01-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0009_remove_question_choice_text_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.BooleanField(default=False),
        ),
    ]
