# Generated by Django 4.0.1 on 2022-01-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0010_alter_choice_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
