# Generated by Django 4.0.1 on 2022-01-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0012_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='remark',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='question',
        ),
    ]
