# Generated by Django 4.0.1 on 2022-01-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0013_new_question_rename_remark_comment_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('theme', models.CharField(max_length=200)),
                ('score', models.CharField(max_length=200)),
            ],
        ),
    ]
